server:
    port: 8001
spring:
    application:
        name: cloud-payment-service
    datasource:
        driver-class-name: org.gjt.mm.mysql.Driver
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/cloud-2020?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root

eureka:
    client:
        fetchRegistry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:7001/eureka
    instance:
        instance-id: payment8001
        lease-renewal-interval-in-seconds: 30
        lease-expiration-duration-in-seconds: 90
        prefer-ip-address: true
mybatis:
    mapperLocations: classpath:mapper/*.xml
    type-aliases-package: com.atguigu.springcloud.entities