server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名

  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/reszp/springcloud-config.git #连接到gitee仓库的springcloud-config项目
          default-label: main #分支
          search-paths:
            - springcloud-config   #搜索目录

  #rabbitMQ配置
  rabbitmq:
    host: 192.168.56.105
    port: 5672
    username: guest
    password: guest

#服务注册到eureka地址
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

##rabbitmq相关配置，暴露bus刷新配置的断点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
