server:
  port: 9001


spring:
  application:
    name: nacos-payment-provider

  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cloud-2020?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root

  cloud:
    nacos:
      discovery:
        server-addr: ${cnetos7.2.ip}:80 # nginx 代理 80


management:
    endpoints:
        web:
            exposure:
                include: '*'


cnetos7.2:
  ip: 192.168.56.105