server:
  port: 7001


eureka:
  instance:
    hostname: localhost #eureka服务端的实例名称
    # 集群配置
    # hostname: 192.168.56.103 #本机ip
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #单机就是自己
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群指向其它eureka servers
      # defaultZone: http://192.168.56.105:7001/eureka/

  server:
    #自我保护模式，当出现网络分区故障、频繁的开启关闭客户端、eureka在短时间内丢失过多客户端时，会进入自我保护模式，即一个服务长时间没有发送心跳，eureka也不会将其删除，默认为true
    enable-self-preservation: true
    #eureka server清理无效节点的时间间隔，默认60000毫秒，即60秒
    eviction-interval-timer-in-ms: 60000
